export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const REPOST_POST_REQUEST = 'REPOST_POST_REQUEST'
export const REPOST_POST_SUCCESS = 'REPOST_POST_SUCCESS'
export const REPOST_POST_FAILURE = 'REPOST_POST_FAILURE'

export const CREATE_REPLY_REQUEST = 'CREATE_REPLY_REQUEST'
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS'
export const CREATE_REPLY_FAILURE = 'CREATE_REPLY_FAILURE'

export const BOOKMARK_POST_REQUEST = 'BOOKMARK_POST_REQUEST'
export const BOOKMARK_POST_SUCCESS = 'BOOKMARK_POST_SUCCESS'
export const BOOKMARK_POST_FAILURE = 'BOOKMARK_POST_FAILURE'

export const HIGHLIGHT_POST_REQUEST = 'HIGHLIGHT_POST_REQUEST'
export const HIGHLIGHT_POST_SUCCESS = 'HIGHLIGHT_POST_SUCCESS'
export const HIGHLIGHT_POST_FAILURE = 'HIGHLIGHT_POST_FAILURE'

export const RETRIEVE_ALL_POSTS_REQUEST = 'RETRIEVE_ALL_POSTS_REQUEST'
export const RETRIEVE_ALL_POSTS_SUCCESS = 'RETRIEVE_ALL_POSTS_SUCCESS'
export const RETRIEVE_ALL_POSTS_FAILURE = 'RETRIEVE_ALL_POSTS_FAILURE'

export const RETRIEVE_POST_BY_ID_REQUEST = 'RETRIEVE_POST_BY_ID_REQUEST'
export const RETRIEVE_POST_BY_ID_SUCCESS = 'RETRIEVE_POST_BY_ID_SUCCESS'
export const RETRIEVE_POST_BY_ID_FAILURE = 'RETRIEVE_POST_BY_ID_FAILURE'

export const RETRIEVE_ALL_USER_POSTS_REQUEST = 'RETRIEVE_ALL_USER_POSTS_REQUEST'
export const RETRIEVE_ALL_USER_POSTS_SUCCESS = 'RETRIEVE_ALL_USER_POSTS_SUCCESS'
export const RETRIEVE_ALL_USER_POSTS_FAILURE = 'RETRIEVE_ALL_USER_POSTS_FAILURE'

export const RETRIEVE_ALL_USER_REPLIES_REQUEST = 'RETRIEVE_ALL_USER_REPLIES_REQUEST'
export const RETRIEVE_ALL_USER_REPLIES_SUCCESS = 'RETRIEVE_ALL_USER_REPLIES_SUCCESS'
export const RETRIEVE_ALL_USER_REPLIES_FAILURE = 'RETRIEVE_ALL_USER_REPLIES_FAILURE'

export const RETRIEVE_POSTS_LIKED_BY_USER_REQUEST = 'RETRIEVE_POSTS_LIKED_BY_USER_REQUEST'
export const RETRIEVE_POSTS_LIKED_BY_USER_SUCCESS = 'RETRIEVE_POSTS_LIKED_BY_USER_SUCCESS'
export const RETRIEVE_POSTS_LIKED_BY_USER_FAILURE = 'RETRIEVE_POSTS_LIKED_BY_USER_FAILURE'

export const RETRIEVE_POSTS_BOOKMARKED_BY_USER_REQUEST = 'RETRIEVE_POSTS_BOOKMARKED_BY_USER_REQUEST'
export const RETRIEVE_POSTS_BOOKMARKED_BY_USER_SUCCESS = 'RETRIEVE_POSTS_BOOKMARKED_BY_USER_SUCCESS'
export const RETRIEVE_POSTS_BOOKMARKED_BY_USER_FAILURE = 'RETRIEVE_POSTS_BOOKMARKED_BY_USER_FAILURE'
