export const LOGOUT = 'LOGOUT'

export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST'
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS'
export const SIGN_IN_USER_FAILURE = 'SIGN_IN_USER_FAILURE'

export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST'
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS'
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE'

export const DELETE_USER_NOTIFICATIONS = 'DELETE_USER_NOTIFICATIONS'

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE'

export const RETRIEVE_USER_BY_ID_REQUEST = 'RETRIEVE_USER_BY_ID_REQUEST'
export const RETRIEVE_USER_BY_ID_SUCCESS = 'RETRIEVE_USER_BY_ID_SUCCESS'
export const RETRIEVE_USER_BY_ID_FAILURE = 'RETRIEVE_USER_BY_ID_FAILURE'

export const FOLLOW_UNFOLLOW_USER_REQUEST = 'FOLLOW_UNFOLLOW_USER_REQUEST'
export const FOLLOW_UNFOLLOW_USER_SUCCESS = 'FOLLOW_UNFOLLOW_USER_SUCCESS'
export const FOLLOW_UNFOLLOW_USER_FAILURE = 'FOLLOW_UNFOLLOW_USER_FAILURE'

export const RETRIEVE_USER_PROFILE_REQUEST = 'RETRIEVE_USER_PROFILE_REQUEST'
export const RETRIEVE_USER_PROFILE_SUCCESS = 'RETRIEVE_USER_PROFILE_SUCCESS'
export const RETRIEVE_USER_PROFILE_FAILURE = 'RETRIEVE_USER_PROFILE_FAILURE'

export const SIGN_IN_USER_WITH_GOOGLE_REQUEST = 'SIGN_IN_USER_WITH_GOOGLE_REQUEST'
export const SIGN_IN_USER_WITH_GOOGLE_SUCCESS = 'SIGN_IN_USER_WITH_GOOGLE_SUCCESS'
export const SIGN_IN_USER_WITH_GOOGLE_FAILURE = 'SIGN_IN_USER_WITH_GOOGLE_FAILURE'

export const MARK_ALL_USER_NOTIFICATIONS_AS_READ = 'MARK_ALL_USER_NOTIFICATIONS_AS_READ'

export const RETRIEVE_USER_NOTIFICATIONS_REQUEST = 'RETRIEVE_USER_NOTIFICATIONS_REQUEST'
export const RETRIEVE_USER_NOTIFICATIONS_SUCCESS = 'RETRIEVE_USER_NOTIFICATIONS_SUCCESS'
export const RETRIEVE_USER_NOTIFICATIONS_FAILURE = 'RETRIEVE_USER_NOTIFICATIONS_FAILURE'

export const SEARCH_USERS_BY_NAME_OR_EMAIL_REQUEST = 'SEARCH_USERS_BY_NAME_OR_EMAIL_REQUEST'
export const SEARCH_USERS_BY_NAME_OR_EMAIL_SUCCESS = 'SEARCH_USERS_BY_NAME_OR_EMAIL_SUCCESS'
export const SEARCH_USERS_BY_NAME_OR_EMAIL_FAILURE = 'SEARCH_USERS_BY_NAME_OR_EMAIL_FAILURE'

export const RETRIEVE_USERS_EXCLUDING_FOLLOWED_REQUEST = 'RETRIEVE_USERS_EXCLUDING_FOLLOWED_REQUEST'
export const RETRIEVE_USERS_EXCLUDING_FOLLOWED_SUCCESS = 'RETRIEVE_USERS_EXCLUDING_FOLLOWED_SUCCESS'
export const RETRIEVE_USERS_EXCLUDING_FOLLOWED_FAILURE = 'RETRIEVE_USERS_EXCLUDING_FOLLOWED_FAILURE'
